// catalog data: brands, categories, and products

const AppData = {
  brands: [
  {
    "name": "HUL",
    "fullName": "Hindustan Unilever",
    "logo": "images/brands/hul.svg",
    "count": "14 Items",
    "pill": "Flat 10% Off",
    "pillType": "green"
  },
  {
    "name": "Coca-Cola",
    "fullName": "The Coca-Cola Company",
    "logo": "images/brands/coca_cola.svg",
    "count": "7 Items",
    "pill": "Chilled Ready",
    "pillType": "blue"
  },
  {
    "name": "PepsiCo",
    "fullName": "PepsiCo India",
    "logo": "images/brands/pepsico.svg",
    "count": "10 Items",
    "pill": "Combo Deals",
    "pillType": "green"
  },
  {
    "name": "ITC",
    "fullName": "ITC Limited",
    "logo": "images/brands/itc.svg",
    "count": "6 Items",
    "pill": "Top Seller",
    "pillType": "amber"
  },
  {
    "name": "Nestle",
    "fullName": "Nestlé India",
    "logo": "images/brands/nestle.svg",
    "count": "6 Items",
    "pill": "Morning Picks",
    "pillType": "blue"
  },
  {
    "name": "Parle",
    "fullName": "Parle Products",
    "logo": "images/brands/parle.svg",
    "count": "5 Items",
    "pill": "Tea Time",
    "pillType": "green"
  },
  {
    "name": "Britannia",
    "fullName": "Britannia Industries",
    "logo": "images/brands/britannia.svg",
    "count": "5 Items",
    "pill": "Fresh Bakes",
    "pillType": "amber"
  },
  {
    "name": "Amul",
    "fullName": "The Taste of India",
    "logo": "images/brands/amul.svg",
    "count": "8 Items",
    "pill": "Dairy Fresh",
    "pillType": "green"
  },
  {
    "name": "Tata",
    "fullName": "Tata Consumer Products",
    "logo": "images/brands/tata.svg",
    "count": "5 Items",
    "pill": "Pure & Trusted",
    "pillType": "blue"
  },
  {
    "name": "Dabur",
    "fullName": "Dabur India",
    "logo": "images/brands/dabur.svg",
    "count": "5 Items",
    "pill": "Herbal Care",
    "pillType": "amber"
  }
],
  categories: [
  {
    "id": "grocery",
    "name": "Groceries & Staples",
    "icon": "images/categories/cat_grocery.svg",
    "faIcon": "fas fa-basket-shopping",
    "tag": "Atta, Rice, Oils"
  },
  {
    "id": "dairy",
    "name": "Dairy & Breakfast",
    "icon": "images/categories/cat_dairy.svg",
    "faIcon": "fas fa-egg",
    "tag": "Milk, Butter, Curd"
  },
  {
    "id": "snacks",
    "name": "Snacks & Munchies",
    "icon": "images/categories/cat_snacks.svg",
    "faIcon": "fas fa-cookie-bite",
    "tag": "Chips, Namkeen, Crisps"
  },
  {
    "id": "beverages",
    "name": "Beverages & Drinks",
    "icon": "images/categories/cat_beverages.svg",
    "faIcon": "fas fa-bottle-water",
    "tag": "Tea, Juices, Sodas"
  },
  {
    "id": "biscuits",
    "name": "Biscuits & Cookies",
    "icon": "images/categories/cat_biscuits.svg",
    "faIcon": "fas fa-cookie",
    "tag": "Cookies, Rusks, Wafers"
  },
  {
    "id": "personal_care",
    "name": "Personal Care",
    "icon": "images/categories/cat_personal_care.svg",
    "faIcon": "fas fa-pump-soap",
    "tag": "Soaps, Creams, Dental"
  },
  {
    "id": "home_care",
    "name": "Cleaning & Home",
    "icon": "images/categories/cat_home_care.svg",
    "faIcon": "fas fa-spray-can-sparkles",
    "tag": "Detergent, Cleaners"
  },
  {
    "id": "pooja",
    "name": "Pooja Essentials",
    "icon": "images/categories/cat_pooja.svg",
    "faIcon": "fas fa-om",
    "tag": "Agbarbatti, Diya Oil"
  }
],
  products: [
  {
    "id": "p1",
    "name": "Parle-G Gold Biscuits",
    "brand": "Parle",
    "category": "Biscuits & Cookies",
    "price": 30,
    "mrp": 30,
    "unit": "800g",
    "usp": "₹3.75 / 100g",
    "rating": 4.8,
    "ratingCount": 1420,
    "image": "images/products/p1.jpg",
    "eta": "10-15 mins",
    "description": "India's favourite biscuit packed with the goodness of milk and wheat. Crisp, crunchy, and golden baked.",
    "highlights": [
      "Classic Indian Tea Partner",
      "Energy Rich",
      "100% Vegetarian"
    ],
    "isFlashDeal": true,
    "discount": 0,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901000314159"
  },
  {
    "id": "p2",
    "name": "Parle Monaco Classic Salted",
    "brand": "Parle",
    "category": "Biscuits & Cookies",
    "price": 30,
    "mrp": 35,
    "unit": "200g",
    "usp": "₹15.00 / 100g",
    "rating": 4.5,
    "ratingCount": 890,
    "image": "images/products/p2.jpg",
    "eta": "10-15 mins",
    "description": "Light, crispy, and crunchy salted crackers with a delicate melt-in-mouth texture.",
    "highlights": [
      "Light & Crispy",
      "Classic Salted",
      "Ideal Party Snack"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901000628318"
  },
  {
    "id": "p3",
    "name": "Parle Krackjack Sweet & Salty",
    "brand": "Parle",
    "category": "Biscuits & Cookies",
    "price": 20,
    "mrp": 25,
    "unit": "200g",
    "usp": "₹10.00 / 100g",
    "rating": 4.4,
    "ratingCount": 760,
    "image": "images/products/p3.jpg",
    "eta": "10-15 mins",
    "description": "The original sweet & salty cracker that gives you two flavours in every crunchy bite.",
    "highlights": [
      "Sweet & Salty",
      "Golden Crunchy",
      "Tea-time favourite"
    ],
    "isFlashDeal": false,
    "discount": 20,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901000942477"
  },
  {
    "id": "p4",
    "name": "Parle Hide & Seek Chocolate Chip",
    "brand": "Parle",
    "category": "Biscuits & Cookies",
    "price": 40,
    "mrp": 45,
    "unit": "300g",
    "usp": "₹13.33 / 100g",
    "rating": 4.7,
    "ratingCount": 1820,
    "image": "images/products/p4.jpg",
    "eta": "10-15 mins",
    "description": "Rich chocolaty cookies loaded with decadent chocolate chips. Every bite is an indulgence.",
    "highlights": [
      "Real Choco Chips",
      "Rich Cocoa",
      "Youth Favourite"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901001256636"
  },
  {
    "id": "p5",
    "name": "Frooti Mango Drink",
    "brand": "Parle",
    "category": "Beverages & Drinks",
    "price": 35,
    "mrp": 40,
    "unit": "600ml",
    "usp": "₹5.83 / 100ml",
    "rating": 4.6,
    "ratingCount": 2100,
    "image": "images/products/p5.jpg",
    "eta": "10-15 mins",
    "description": "Refreshing juicy mango drink made with ripe Totapuri mango pulp. Made with real mango love.",
    "highlights": [
      "Real Mango Pulp",
      "Juicy & Refreshing",
      "Best Served Chilled"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901001570795"
  },
  {
    "id": "p6",
    "name": "Britannia Good Day Butter Cookies",
    "brand": "Britannia",
    "category": "Biscuits & Cookies",
    "price": 55,
    "mrp": 60,
    "unit": "400g",
    "usp": "₹13.75 / 100g",
    "rating": 4.7,
    "ratingCount": 1640,
    "image": "images/products/p6.jpg",
    "eta": "10-15 mins",
    "description": "Rich, melt-in-the-mouth butter cookies with a delightful smile on every cookie.",
    "highlights": [
      "Rich Butter Flavor",
      "Crisp Texture",
      "Baked to Perfection"
    ],
    "isFlashDeal": false,
    "discount": 8,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901001884954"
  },
  {
    "id": "p7",
    "name": "Britannia Good Day Cashew Cookies",
    "brand": "Britannia",
    "category": "Biscuits & Cookies",
    "price": 90,
    "mrp": 100,
    "unit": "600g",
    "usp": "₹15.00 / 100g",
    "rating": 4.7,
    "ratingCount": 1950,
    "image": "images/products/p7.jpg",
    "eta": "10-15 mins",
    "description": "Crunchy cookies studded with buttery roasted cashew nuts for a rich, satisfying crunch.",
    "highlights": [
      "Real Cashews",
      "Golden Baked",
      "Melt in Mouth"
    ],
    "isFlashDeal": true,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901002199113"
  },
  {
    "id": "p8",
    "name": "Britannia Marie Gold Biscuits",
    "brand": "Britannia",
    "category": "Biscuits & Cookies",
    "price": 55,
    "mrp": 60,
    "unit": "600g",
    "usp": "₹9.17 / 100g",
    "rating": 4.6,
    "ratingCount": 1430,
    "image": "images/products/p8.jpg",
    "eta": "10-15 mins",
    "description": "Crisp, light tea-time biscuits fortified with 10 essential vitamins and minerals.",
    "highlights": [
      "Zero Trans Fat",
      "10 Essential Vitamins",
      "Crisp & Light"
    ],
    "isFlashDeal": false,
    "discount": 8,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901002513272"
  },
  {
    "id": "p9",
    "name": "Britannia Bourbon Chocolate Cream",
    "brand": "Britannia",
    "category": "Biscuits & Cookies",
    "price": 50,
    "mrp": 55,
    "unit": "600g",
    "usp": "₹8.33 / 100g",
    "rating": 4.6,
    "ratingCount": 1280,
    "image": "images/products/p9.jpg",
    "eta": "10-15 mins",
    "description": "Original chocolate sandwich biscuits with smooth dark chocolate cream and sugar crystals on top.",
    "highlights": [
      "Rich Choco Cream",
      "Sugar Crystals",
      "Crisp Crust"
    ],
    "isFlashDeal": false,
    "discount": 9,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901002827431"
  },
  {
    "id": "p10",
    "name": "Britannia NutriChoice Digestive",
    "brand": "Britannia",
    "category": "Biscuits & Cookies",
    "price": 60,
    "mrp": 65,
    "unit": "400g",
    "usp": "₹15.00 / 100g",
    "rating": 4.5,
    "ratingCount": 1150,
    "image": "images/products/p10.jpg",
    "eta": "10-15 mins",
    "description": "High fibre whole wheat digestive biscuits that support your daily digestive wellness.",
    "highlights": [
      "High Dietary Fibre",
      "100% Whole Wheat",
      "No Added Preservatives"
    ],
    "isFlashDeal": false,
    "discount": 8,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901003141590"
  },
  {
    "id": "p11",
    "name": "Amul Butter Pasteurised",
    "brand": "Amul",
    "category": "Dairy & Breakfast",
    "price": 259,
    "mrp": 270,
    "unit": "500g",
    "usp": "₹51.80 / 100g",
    "rating": 4.9,
    "ratingCount": 4500,
    "image": "images/products/p11.jpg",
    "eta": "10-15 mins",
    "description": "Utterly Butterly Delicious pasteurised table butter made with pure cow & buffalo milk cream.",
    "highlights": [
      "100% Pure Milk Butter",
      "Iconic Taste",
      "Must-have Breakfast Staple"
    ],
    "isFlashDeal": true,
    "discount": 4,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901003455749"
  },
  {
    "id": "p12",
    "name": "Amul Taaza Toned Fresh Milk",
    "brand": "Amul",
    "category": "Dairy & Breakfast",
    "price": 60,
    "mrp": 62,
    "unit": "1L",
    "usp": "₹60.0 / L",
    "rating": 4.8,
    "ratingCount": 3800,
    "image": "images/products/p12.jpg",
    "eta": "10-15 mins",
    "description": "Homogenised toned long-life milk with 3.0% fat. Fresh, hygienic, and nutritious.",
    "highlights": [
      "UHT Treated",
      "No Preservatives",
      "Rich in Calcium & Protein"
    ],
    "isFlashDeal": false,
    "discount": 3,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901003769908"
  },
  {
    "id": "p13",
    "name": "Amul Gold Full Cream Fresh Milk",
    "brand": "Amul",
    "category": "Dairy & Breakfast",
    "price": 66,
    "mrp": 68,
    "unit": "1L",
    "usp": "₹66.0 / L",
    "rating": 4.8,
    "ratingCount": 3200,
    "image": "images/products/p13.jpg",
    "eta": "10-15 mins",
    "description": "Full cream homogenised milk with 6.0% fat. Thick, creamy, and ideal for tea, coffee, and desserts.",
    "highlights": [
      "6.0% Milk Fat",
      "Rich & Creamy",
      "Energy Dense"
    ],
    "isFlashDeal": false,
    "discount": 3,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901004084067"
  },
  {
    "id": "p14",
    "name": "Amul Processed Cheese Slices",
    "brand": "Amul",
    "category": "Dairy & Breakfast",
    "price": 130,
    "mrp": 140,
    "unit": "200g (10 Slices)",
    "usp": "₹130 / 200g (10 Slices)",
    "rating": 4.7,
    "ratingCount": 2100,
    "image": "images/products/p14.jpg",
    "eta": "10-15 mins",
    "description": "Individually wrapped creamy processed cheese slices, perfect for sandwiches and burgers.",
    "highlights": [
      "100% Pure Milk Cheese",
      "Individually Wrapped",
      "Melts Easily"
    ],
    "isFlashDeal": true,
    "discount": 7,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901004398226"
  },
  {
    "id": "p15",
    "name": "Amul Masti Dahi Curd",
    "brand": "Amul",
    "category": "Dairy & Breakfast",
    "price": 62,
    "mrp": 65,
    "unit": "1kg",
    "usp": "₹62.0 / kg",
    "rating": 4.7,
    "ratingCount": 1900,
    "image": "images/products/p15.jpg",
    "eta": "10-15 mins",
    "description": "Thick, creamy, and mildly sour natural curd made from pasteurised toned milk.",
    "highlights": [
      "Natural Probiotics",
      "Thick & Creamy",
      "No Gelatin or Preservatives"
    ],
    "isFlashDeal": false,
    "discount": 5,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901004712385"
  },
  {
    "id": "p16",
    "name": "Amul Pure Cow Ghee",
    "brand": "Amul",
    "category": "Dairy & Breakfast",
    "price": 310,
    "mrp": 330,
    "unit": "500ml",
    "usp": "₹62.00 / 100ml",
    "rating": 4.8,
    "ratingCount": 2600,
    "image": "images/products/p16.jpg",
    "eta": "10-15 mins",
    "description": "Aromatic, golden clarified butter made from fresh dairy milk. Enhances taste of every dish.",
    "highlights": [
      "Rich Aroma",
      "Traditional Granular Texture",
      "High Smoke Point"
    ],
    "isFlashDeal": false,
    "discount": 6,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901005026544"
  },
  {
    "id": "p17",
    "name": "Amul 55% Dark Chocolate",
    "brand": "Amul",
    "category": "Snacks & Munchies",
    "price": 195,
    "mrp": 220,
    "unit": "150g",
    "usp": "₹130.00 / 100g",
    "rating": 4.6,
    "ratingCount": 1400,
    "image": "images/products/p17.jpg",
    "eta": "10-15 mins",
    "description": "Exquisite dark chocolate bar crafted with single-origin rich cocoa beans.",
    "highlights": [
      "55% Cocoa",
      "Zero Added Milk Fat",
      "Antioxidant Rich"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901005340703"
  },
  {
    "id": "p18",
    "name": "Coca-Cola Original Taste",
    "brand": "Coca-Cola",
    "category": "Beverages & Drinks",
    "price": 45,
    "mrp": 50,
    "unit": "750ml",
    "usp": "₹6.00 / 100ml",
    "rating": 4.7,
    "ratingCount": 5100,
    "image": "images/products/p18.jpg",
    "eta": "10-15 mins",
    "description": "The world's favourite sparkling soft drink. Crisp, refreshing, and full of upliftment.",
    "highlights": [
      "Original Formula",
      "Best Served Ice Cold",
      "Iconic Refreshment"
    ],
    "isFlashDeal": true,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901005654862"
  },
  {
    "id": "p19",
    "name": "Thums Up Toofani Cola",
    "brand": "Coca-Cola",
    "category": "Beverages & Drinks",
    "price": 45,
    "mrp": 50,
    "unit": "750ml",
    "usp": "₹6.00 / 100ml",
    "rating": 4.8,
    "ratingCount": 6200,
    "image": "images/products/p19.jpg",
    "eta": "10-15 mins",
    "description": "India's strongest cola with a powerful spicy kick and high carbonation.",
    "highlights": [
      "Strong Fizzy Punch",
      "Spicy Cola Taste",
      "Taste the Thunder"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901005969021"
  },
  {
    "id": "p20",
    "name": "Sprite Clear Lime Soft Drink",
    "brand": "Coca-Cola",
    "category": "Beverages & Drinks",
    "price": 40,
    "mrp": 45,
    "unit": "750ml",
    "usp": "₹5.33 / 100ml",
    "rating": 4.6,
    "ratingCount": 3900,
    "image": "images/products/p20.jpg",
    "eta": "10-15 mins",
    "description": "Clear, sparkling lemon-lime flavoured soda that cuts through thirst instantly.",
    "highlights": [
      "Crisp Lemon Lime",
      "100% Clear",
      "Maximum Refreshment"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901006283180"
  },
  {
    "id": "p21",
    "name": "Maaza Mango Pulp Beverage",
    "brand": "Coca-Cola",
    "category": "Beverages & Drinks",
    "price": 35,
    "mrp": 40,
    "unit": "600ml",
    "usp": "₹5.83 / 100ml",
    "rating": 4.7,
    "ratingCount": 4100,
    "image": "images/products/p21.jpg",
    "eta": "10-15 mins",
    "description": "Thick and luscious mango drink made from real Alphonso and Totapuri mangoes.",
    "highlights": [
      "Alphonso Mango Touch",
      "Thick & Sweet",
      "Dildaar Mango Taste"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901006597339"
  },
  {
    "id": "p22",
    "name": "Limca Lime 'n' Lemoni",
    "brand": "Coca-Cola",
    "category": "Beverages & Drinks",
    "price": 40,
    "mrp": 45,
    "unit": "750ml",
    "usp": "₹5.33 / 100ml",
    "rating": 4.5,
    "ratingCount": 2400,
    "image": "images/products/p22.jpg",
    "eta": "10-15 mins",
    "description": "Cloudy citrus soft drink with a fizzy lemon burst that revives your senses.",
    "highlights": [
      "Real Lemon Juice Touch",
      "Cloudy & Zesty",
      "Zero Caffeine"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901006911498"
  },
  {
    "id": "p23",
    "name": "Fanta Orange Fizzy Drink",
    "brand": "Coca-Cola",
    "category": "Beverages & Drinks",
    "price": 40,
    "mrp": 45,
    "unit": "750ml",
    "usp": "₹5.33 / 100ml",
    "rating": 4.4,
    "ratingCount": 2800,
    "image": "images/products/p23.jpg",
    "eta": "10-15 mins",
    "description": "Bright, vibrant orange-flavoured sparkling beverage with playful fizz.",
    "highlights": [
      "Fruit Orange Flavour",
      "Vibrant & Fruity",
      "Caffeine Free"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901007225657"
  },
  {
    "id": "p24",
    "name": "Kinley Club Soda Water",
    "brand": "Coca-Cola",
    "category": "Beverages & Drinks",
    "price": 25,
    "mrp": 30,
    "unit": "750ml",
    "usp": "₹3.33 / 100ml",
    "rating": 4.4,
    "ratingCount": 1900,
    "image": "images/products/p24.jpg",
    "eta": "10-15 mins",
    "description": "Extra bubbly and crisp sparkling soda water with balanced mineral salts.",
    "highlights": [
      "Extra Carbonation",
      "Zero Sugar",
      "Pure Taste"
    ],
    "isFlashDeal": false,
    "discount": 17,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901007539816"
  },
  {
    "id": "p25",
    "name": "Pepsi Cola Carbonated Drink",
    "brand": "PepsiCo",
    "category": "Beverages & Drinks",
    "price": 40,
    "mrp": 45,
    "unit": "750ml",
    "usp": "₹5.33 / 100ml",
    "rating": 4.6,
    "ratingCount": 3800,
    "image": "images/products/p25.jpg",
    "eta": "10-15 mins",
    "description": "Bold, invigorating cola beverage with a crisp, refreshing sweetness.",
    "highlights": [
      "Bold Cola Taste",
      "Sparkling Fizz",
      "Party Essential"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901007853975"
  },
  {
    "id": "p26",
    "name": "Mountain Dew Citrus Blast",
    "brand": "PepsiCo",
    "category": "Beverages & Drinks",
    "price": 40,
    "mrp": 45,
    "unit": "750ml",
    "usp": "₹5.33 / 100ml",
    "rating": 4.7,
    "ratingCount": 4200,
    "image": "images/products/p26.jpg",
    "eta": "10-15 mins",
    "description": "High-octane neon citrus soft drink designed to ignite your fearless adventurous side.",
    "highlights": [
      "Neon Citrus Punch",
      "Caffeine Boost",
      "Darr Ke Aage Jeet Hai"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901008168134"
  },
  {
    "id": "p27",
    "name": "Mirinda Orange Soda",
    "brand": "PepsiCo",
    "category": "Beverages & Drinks",
    "price": 35,
    "mrp": 40,
    "unit": "750ml",
    "usp": "₹4.67 / 100ml",
    "rating": 4.4,
    "ratingCount": 2200,
    "image": "images/products/p27.jpg",
    "eta": "10-15 mins",
    "description": "Tangy orange sparkling drink with bold fruity aroma and zesty bubble burst.",
    "highlights": [
      "Tangy Orange Flavor",
      "Sweet & Punchy",
      "Youthful Energy"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901008482293"
  },
  {
    "id": "p28",
    "name": "7UP Lemon Lime Soda",
    "brand": "PepsiCo",
    "category": "Beverages & Drinks",
    "price": 35,
    "mrp": 40,
    "unit": "750ml",
    "usp": "₹4.67 / 100ml",
    "rating": 4.5,
    "ratingCount": 2900,
    "image": "images/products/p28.jpg",
    "eta": "10-15 mins",
    "description": "Natural lemon and lime flavours infused in a crystal clear bubbly drink.",
    "highlights": [
      "100% Natural Flavors",
      "Caffeine Free",
      "Crisp & Clean"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901008796452"
  },
  {
    "id": "p29",
    "name": "Sting Energy Drink Berry Blast",
    "brand": "PepsiCo",
    "category": "Beverages & Drinks",
    "price": 25,
    "mrp": 30,
    "unit": "250ml",
    "usp": "₹10.00 / 100ml",
    "rating": 4.6,
    "ratingCount": 5400,
    "image": "images/products/p29.jpg",
    "eta": "10-15 mins",
    "description": "Electrifying red energy drink with sweet berry flavour and revitalising caffeine.",
    "highlights": [
      "Instant Energy",
      "Berry Flavour",
      "With Taurine & B-Vitamins"
    ],
    "isFlashDeal": true,
    "discount": 17,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901009110611"
  },
  {
    "id": "p30",
    "name": "Lay's India's Magic Masala",
    "brand": "PepsiCo",
    "category": "Snacks & Munchies",
    "price": 30,
    "mrp": 35,
    "unit": "78g",
    "usp": "₹38.46 / 100g",
    "rating": 4.8,
    "ratingCount": 6700,
    "image": "images/products/p30.jpg",
    "eta": "10-15 mins",
    "description": "Thin, crunchy potato chips tossed in an irresistible blend of authentic Indian spices.",
    "highlights": [
      "Spicy Masala Flavor",
      "Farm-grown Potatoes",
      "Crisp Crunch"
    ],
    "isFlashDeal": true,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901009424770"
  },
  {
    "id": "p31",
    "name": "Lay's American Style Cream & Onion",
    "brand": "PepsiCo",
    "category": "Snacks & Munchies",
    "price": 30,
    "mrp": 35,
    "unit": "78g",
    "usp": "₹38.46 / 100g",
    "rating": 4.7,
    "ratingCount": 5900,
    "image": "images/products/p31.jpg",
    "eta": "10-15 mins",
    "description": "Crisp potato wafers coated with mild sour cream and sweet fragrant green onions.",
    "highlights": [
      "Cream & Onion Fusion",
      "Golden Crisp",
      "Crowd Favourite"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901009738929"
  },
  {
    "id": "p32",
    "name": "Kurkure Masala Munch Namkeen",
    "brand": "PepsiCo",
    "category": "Snacks & Munchies",
    "price": 40,
    "mrp": 45,
    "unit": "105g",
    "usp": "₹38.10 / 100g",
    "rating": 4.7,
    "ratingCount": 5800,
    "image": "images/products/p32.jpg",
    "eta": "10-15 mins",
    "description": "Crunchy, tedha corn-puff snacks seasoned with punchy Indian chatpata spices.",
    "highlights": [
      "Chatpata Masala",
      "Crunchy Corn Puffs",
      "100% Vegetarian"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901010053088"
  },
  {
    "id": "p33",
    "name": "Kurkure Chilli Chatka Namkeen",
    "brand": "PepsiCo",
    "category": "Snacks & Munchies",
    "price": 40,
    "mrp": 45,
    "unit": "105g",
    "usp": "₹38.10 / 100g",
    "rating": 4.5,
    "ratingCount": 3100,
    "image": "images/products/p33.jpg",
    "eta": "10-15 mins",
    "description": "Bold fiery red chilli crisps with tangy lime zest that wake up your taste buds.",
    "highlights": [
      "Spicy Chilli Kick",
      "Tangy Twist",
      "Crunchy Texture"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901010367247"
  },
  {
    "id": "p34",
    "name": "Tropicana 100% Mixed Fruit Juice",
    "brand": "PepsiCo",
    "category": "Beverages & Drinks",
    "price": 120,
    "mrp": 135,
    "unit": "1L",
    "usp": "₹120.0 / L",
    "rating": 4.6,
    "ratingCount": 2400,
    "image": "images/products/p34.jpg",
    "eta": "10-15 mins",
    "description": "Wholesome blend of apples, oranges, grapes, and apricots with no added sugar.",
    "highlights": [
      "No Added Sugar",
      "Rich in Vitamin C",
      "Pure Fruit Goodness"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901010681406"
  },
  {
    "id": "p35",
    "name": "Dove Cream Beauty Bathing Bar",
    "brand": "HUL",
    "category": "Personal Care",
    "price": 70,
    "mrp": 80,
    "unit": "100g",
    "usp": "₹70.00 / 100g",
    "rating": 4.8,
    "ratingCount": 4200,
    "image": "images/products/p35.jpg",
    "eta": "10-15 mins",
    "description": "Moisturising bathing bar formulated with 1/4 moisturising cream for radiant, soft skin.",
    "highlights": [
      "1/4 Moisturising Cream",
      "Dermatologically Tested",
      "Doesn't Dry Skin"
    ],
    "isFlashDeal": true,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901010995565"
  },
  {
    "id": "p36",
    "name": "Pears Pure & Gentle Glycerin Soap",
    "brand": "HUL",
    "category": "Personal Care",
    "price": 55,
    "mrp": 60,
    "unit": "125g",
    "usp": "₹44.00 / 100g",
    "rating": 4.7,
    "ratingCount": 3400,
    "image": "images/products/p36.jpg",
    "eta": "10-15 mins",
    "description": "Transparent pure glycerin soap with 98% pure glycerin and natural oils.",
    "highlights": [
      "Pure Glycerin",
      "Gentle on Sensitive Skin",
      "Natural Oils"
    ],
    "isFlashDeal": false,
    "discount": 8,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901011309724"
  },
  {
    "id": "p37",
    "name": "Lifebuoy Total Germ Protection Soap",
    "brand": "HUL",
    "category": "Personal Care",
    "price": 40,
    "mrp": 45,
    "unit": "125g",
    "usp": "₹32.00 / 100g",
    "rating": 4.6,
    "ratingCount": 2800,
    "image": "images/products/p37.jpg",
    "eta": "10-15 mins",
    "description": "Proven 99.9% germ protection with Activ Silver formula for the whole family.",
    "highlights": [
      "Activ Silver Formula",
      "10x Germ Protection",
      "Invigorating Cleanse"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901011623883"
  },
  {
    "id": "p38",
    "name": "Lux Velvet Touch Jasmine Soap",
    "brand": "HUL",
    "category": "Personal Care",
    "price": 45,
    "mrp": 50,
    "unit": "125g",
    "usp": "₹36.00 / 100g",
    "rating": 4.5,
    "ratingCount": 2500,
    "image": "images/products/p38.jpg",
    "eta": "10-15 mins",
    "description": "Fragrant bathing soap infused with rich Jasmine flower extracts and almond oil.",
    "highlights": [
      "Jasmine & Almond Oil",
      "Silky Smooth Foam",
      "Floral Perfume"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901011938042"
  },
  {
    "id": "p39",
    "name": "Sunsilk Lusciously Thick & Long",
    "brand": "HUL",
    "category": "Personal Care",
    "price": 280,
    "mrp": 320,
    "unit": "340ml",
    "usp": "₹82.35 / 100ml",
    "rating": 4.5,
    "ratingCount": 3100,
    "image": "images/products/p39.jpg",
    "eta": "10-15 mins",
    "description": "Co-created with hair experts, enriched with Keratin Yoghurt Complex for thick, bouncy hair.",
    "highlights": [
      "Keratin Yoghurt Complex",
      "2x Thicker Looking Hair",
      "Nourishing Care"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901012252201"
  },
  {
    "id": "p40",
    "name": "Clinic Plus Strong & Long Shampoo",
    "brand": "HUL",
    "category": "Personal Care",
    "price": 190,
    "mrp": 220,
    "unit": "340ml",
    "usp": "₹55.88 / 100ml",
    "rating": 4.6,
    "ratingCount": 3700,
    "image": "images/products/p40.jpg",
    "eta": "10-15 mins",
    "description": "Nourishing milk protein shampoo that penetrates into hair strands to build strength from root to tip.",
    "highlights": [
      "Milk Protein Formula",
      "Reduces Hair Fall",
      "Safe for Daily Use"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901012566360"
  },
  {
    "id": "p41",
    "name": "Vaseline Original Pure Petroleum Jelly",
    "brand": "HUL",
    "category": "Personal Care",
    "price": 185,
    "mrp": 210,
    "unit": "250ml",
    "usp": "₹74.00 / 100ml",
    "rating": 4.8,
    "ratingCount": 4900,
    "image": "images/products/p41.jpg",
    "eta": "10-15 mins",
    "description": "Triple-purified hypoallergenic wonder jelly that locks in moisture to heal dry skin.",
    "highlights": [
      "100% Pure Jelly",
      "Triple Purified",
      "Heals Dry Cracked Skin"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901012880519"
  },
  {
    "id": "p42",
    "name": "Surf Excel Easy Wash Detergent Powder",
    "brand": "HUL",
    "category": "Cleaning & Home",
    "price": 315,
    "mrp": 360,
    "unit": "2kg",
    "usp": "₹157.5 / kg",
    "rating": 4.8,
    "ratingCount": 4400,
    "image": "images/products/p42.jpg",
    "eta": "10-15 mins",
    "description": "Super fine laundry powder with engineered stain remover particles for effortless stain removal.",
    "highlights": [
      "Stain Removal Particles",
      "Easy Dissolve",
      "Keeps Clothes Bright"
    ],
    "isFlashDeal": true,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901013194678"
  },
  {
    "id": "p43",
    "name": "Rin Advanced Detergent Powder",
    "brand": "HUL",
    "category": "Cleaning & Home",
    "price": 195,
    "mrp": 220,
    "unit": "1.5kg",
    "usp": "₹130.0 / kg",
    "rating": 4.5,
    "ratingCount": 2600,
    "image": "images/products/p43.jpg",
    "eta": "10-15 mins",
    "description": "Delivers dazzling white clothes with bright clean technology and fresh floral fragrance.",
    "highlights": [
      "Bright Clean Technology",
      "Dazzling Whites",
      "Fresh Fragrance"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901013508837"
  },
  {
    "id": "p44",
    "name": "Vim Dishwash Gel Lemon",
    "brand": "HUL",
    "category": "Cleaning & Home",
    "price": 155,
    "mrp": 170,
    "unit": "750ml",
    "usp": "₹20.67 / 100ml",
    "rating": 4.7,
    "ratingCount": 4800,
    "image": "images/products/p44.jpg",
    "eta": "10-15 mins",
    "description": "Concentrated dishwash liquid with the power of 100 lemons. Cleans grease in 1 swipe.",
    "highlights": [
      "Power of 100 Lemons",
      "Zero Residue",
      "Gentle on Hands"
    ],
    "isFlashDeal": true,
    "discount": 9,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901013822996"
  },
  {
    "id": "p45",
    "name": "Brooke Bond Red Label Tea",
    "brand": "HUL",
    "category": "Beverages & Drinks",
    "price": 250,
    "mrp": 280,
    "unit": "500g",
    "usp": "₹50.00 / 100g",
    "rating": 4.7,
    "ratingCount": 3900,
    "image": "images/products/p45.jpg",
    "eta": "10-15 mins",
    "description": "Carefully selected CTC tea leaves with unmatched aroma, color, and rich brisk taste.",
    "highlights": [
      "Swad Apnepan Ka",
      "Rich Aroma",
      "Strong CTC Brew"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901014137155"
  },
  {
    "id": "p46",
    "name": "Brooke Bond Taj Mahal Tea",
    "brand": "HUL",
    "category": "Beverages & Drinks",
    "price": 275,
    "mrp": 310,
    "unit": "500g",
    "usp": "₹55.00 / 100g",
    "rating": 4.8,
    "ratingCount": 2800,
    "image": "images/products/p46.jpg",
    "eta": "10-15 mins",
    "description": "Crafted with precious tea leaves containing high essence flavour buds for royalty.",
    "highlights": [
      "High Flavour CTC",
      "Golden Amber Hue",
      "Wah Taj Taste"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901014451314"
  },
  {
    "id": "p47",
    "name": "Bru Instant Coffee Granules",
    "brand": "HUL",
    "category": "Beverages & Drinks",
    "price": 185,
    "mrp": 215,
    "unit": "200g",
    "usp": "₹92.50 / 100g",
    "rating": 4.6,
    "ratingCount": 2600,
    "image": "images/products/p47.jpg",
    "eta": "10-15 mins",
    "description": "Aromatic blend of 70% coffee and 30% chicory roasted to perfection for strong taste.",
    "highlights": [
      "Roasted Coffee & Chicory",
      "Instant Aroma",
      "Warm South Indian Heritage"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901014765473"
  },
  {
    "id": "p48",
    "name": "Kissan Mixed Fruit Jam",
    "brand": "HUL",
    "category": "Dairy & Breakfast",
    "price": 130,
    "mrp": 145,
    "unit": "500g",
    "usp": "₹26.00 / 100g",
    "rating": 4.6,
    "ratingCount": 3100,
    "image": "images/products/p48.jpg",
    "eta": "10-15 mins",
    "description": "Delicious sweet spread made with 8 real fruits including apple, mango, and papaya.",
    "highlights": [
      "8 Real Fruits Blend",
      "Smooth Spreadable",
      "Breakfast Classic"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901015079632"
  },
  {
    "id": "p49",
    "name": "Dabur Red Ayurvedic Toothpaste",
    "brand": "Dabur",
    "category": "Personal Care",
    "price": 90,
    "mrp": 100,
    "unit": "300g",
    "usp": "₹30.00 / 100g",
    "rating": 4.7,
    "ratingCount": 3300,
    "image": "images/products/p49.jpg",
    "eta": "10-15 mins",
    "description": "India's No.1 Ayurvedic paste packed with clove, pudina, and 13 potent natural herbs.",
    "highlights": [
      "13 Potent Herbs",
      "Fights 7 Dental Problems",
      "Protects Enamel"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901015393791"
  },
  {
    "id": "p50",
    "name": "Dabur 100% Pure Honey",
    "brand": "Dabur",
    "category": "Groceries & Staples",
    "price": 199,
    "mrp": 225,
    "unit": "500g",
    "usp": "₹39.80 / 100g",
    "rating": 4.8,
    "ratingCount": 4600,
    "image": "images/products/p50.jpg",
    "eta": "10-15 mins",
    "description": "100% pure NMR-tested honey sourced from natural bee farms. Rich in natural antioxidants.",
    "highlights": [
      "NMR Tested Pure",
      "Zero Sugar Adulteration",
      "Natural Immunity Booster"
    ],
    "isFlashDeal": true,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901015707950"
  },
  {
    "id": "p51",
    "name": "Dabur Chyawanprash Awaleha",
    "brand": "Dabur",
    "category": "Groceries & Staples",
    "price": 290,
    "mrp": 330,
    "unit": "1kg",
    "usp": "₹290.0 / kg",
    "rating": 4.7,
    "ratingCount": 3700,
    "image": "images/products/p51.jpg",
    "eta": "10-15 mins",
    "description": "Time-tested Ayurvedic formulation enriched with Amla and over 40 natural herbs.",
    "highlights": [
      "2x Immunity",
      "With Fresh Amla",
      "Clinically Proven"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901016022109"
  },
  {
    "id": "p52",
    "name": "Dabur Amla Nourishing Hair Oil",
    "brand": "Dabur",
    "category": "Personal Care",
    "price": 180,
    "mrp": 200,
    "unit": "300ml",
    "usp": "₹60.00 / 100ml",
    "rating": 4.6,
    "ratingCount": 2700,
    "image": "images/products/p52.jpg",
    "eta": "10-15 mins",
    "description": "Enriched with real Indian gooseberry (Amla) to stimulate roots and maintain natural black shine.",
    "highlights": [
      "Natural Amla Extract",
      "Strengthens Roots",
      "Prevents Premature Greying"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901016336268"
  },
  {
    "id": "p53",
    "name": "Dabur Hajmola Regular Tablets",
    "brand": "Dabur",
    "category": "Snacks & Munchies",
    "price": 55,
    "mrp": 65,
    "unit": "120 tabs",
    "usp": "₹55 / 120 tabs",
    "rating": 4.8,
    "ratingCount": 4900,
    "image": "images/products/p53.jpg",
    "eta": "10-15 mins",
    "description": "Legendary digestive chewable tablets combining traditional Indian culinary herbs and spices.",
    "highlights": [
      "Chatpata Digestive",
      "Traditional Spices",
      "Post-meal Favorite"
    ],
    "isFlashDeal": false,
    "discount": 15,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901016650427"
  },
  {
    "id": "p54",
    "name": "Aashirvaad Superior MP Sharbati Atta",
    "brand": "ITC",
    "category": "Groceries & Staples",
    "price": 480,
    "mrp": 535,
    "unit": "10kg",
    "usp": "₹48.0 / kg",
    "rating": 4.8,
    "ratingCount": 5800,
    "image": "images/products/p54.jpg",
    "eta": "10-15 mins",
    "description": "100% whole wheat flour ground from heavy golden Sharbati wheat grains of Madhya Pradesh.",
    "highlights": [
      "0% Maida, 100% Atta",
      "Extra Soft Rotis",
      "High Dietary Fibre"
    ],
    "isFlashDeal": true,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901016964586"
  },
  {
    "id": "p55",
    "name": "Sunfeast Dark Fantasy Choco Fills",
    "brand": "ITC",
    "category": "Biscuits & Cookies",
    "price": 40,
    "mrp": 45,
    "unit": "75g",
    "usp": "₹53.33 / 100g",
    "rating": 4.8,
    "ratingCount": 4200,
    "image": "images/products/p55.jpg",
    "eta": "10-15 mins",
    "description": "Crisp baked chocolate crust hiding a molten, velvety chocolate centre.",
    "highlights": [
      "Molten Choco Core",
      "Pure Indulgence",
      "Warm & Serve"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901017278745"
  },
  {
    "id": "p56",
    "name": "Sunfeast Mom's Magic Butter Cookies",
    "brand": "ITC",
    "category": "Biscuits & Cookies",
    "price": 90,
    "mrp": 100,
    "unit": "600g",
    "usp": "₹15.00 / 100g",
    "rating": 4.6,
    "ratingCount": 2300,
    "image": "images/products/p56.jpg",
    "eta": "10-15 mins",
    "description": "Loaded with roasted butter and rich cashews for a homely cookie experience.",
    "highlights": [
      "Rich Roasted Cashews",
      "Melt in Mouth",
      "Just like Mom's baking"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901017592904"
  },
  {
    "id": "p57",
    "name": "Bingo Mad Angles Achaari Masti",
    "brand": "ITC",
    "category": "Snacks & Munchies",
    "price": 30,
    "mrp": 35,
    "unit": "130g",
    "usp": "₹23.08 / 100g",
    "rating": 4.5,
    "ratingCount": 2100,
    "image": "images/products/p57.jpg",
    "eta": "10-15 mins",
    "description": "Unique triangle-shaped corn crisps tossed in pungent mango pickle seasoning.",
    "highlights": [
      "Zesty Achaari Flavor",
      "Triangle Crisps",
      "Maximum Crunch"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901017907063"
  },
  {
    "id": "p58",
    "name": "ITC Mangaldeep Sandalwood Agarbatti",
    "brand": "ITC",
    "category": "Pooja Essentials",
    "price": 45,
    "mrp": 50,
    "unit": "Pack of 80 Sticks",
    "usp": "₹0.56 / stick",
    "rating": 4.6,
    "ratingCount": 3200,
    "image": "images/products/p58.jpg",
    "eta": "10-15 mins",
    "description": "Fragrant pure sandalwood incense sticks crafted by ITC Mangaldeep for daily devotional pooja and prayer.",
    "highlights": [
      "Pure Sandalwood Aroma",
      "Long 45-Min Burning",
      "Zero Toxic Fumes"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901018221222"
  },
  {
    "id": "p59",
    "name": "Maggi 2-Minute Masala Instant Noodles",
    "brand": "Nestle",
    "category": "Snacks & Munchies",
    "price": 14,
    "mrp": 15,
    "unit": "70g",
    "usp": "₹20.00 / 100g",
    "rating": 4.9,
    "ratingCount": 9800,
    "image": "images/products/p59.jpg",
    "eta": "10-15 mins",
    "description": "India's beloved comfort food. Quick noodles infused with aromatic roasted spices.",
    "highlights": [
      "Ready in 2 Minutes",
      "Signature Tastemaker",
      "Goodness of Iron"
    ],
    "isFlashDeal": true,
    "discount": 7,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901018535381"
  },
  {
    "id": "p60",
    "name": "Mangaldeep Pure Bhimseni Camphor",
    "brand": "ITC",
    "category": "Pooja Essentials",
    "price": 85,
    "mrp": 99,
    "unit": "100g Jar",
    "usp": "₹85.00 / 100g",
    "rating": 4.9,
    "ratingCount": 7400,
    "image": "images/products/p60.jpg",
    "eta": "10-15 mins",
    "description": "100% pure Bhimseni camphor crystals for daily aarti, leaving zero ash and spreading divine spiritual aura.",
    "highlights": [
      "100% Pure Camphor",
      "Leaves Zero Ash",
      "Aromatic & Spiritual"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901018849540"
  },
  {
    "id": "p61",
    "name": "Maggi Rich Tomato Ketchup",
    "brand": "Nestle",
    "category": "Groceries & Staples",
    "price": 155,
    "mrp": 175,
    "unit": "1kg",
    "usp": "₹155.0 / kg",
    "rating": 4.6,
    "ratingCount": 3800,
    "image": "images/products/p61.jpg",
    "eta": "10-15 mins",
    "description": "Sweet and tangy tomato sauce prepared from vine-ripened red tomatoes.",
    "highlights": [
      "Sun-ripened Tomatoes",
      "Thick & Glossy",
      "Squeezy Pour"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901019163699"
  },
  {
    "id": "p62",
    "name": "Nescafe Classic Instant Pure Coffee",
    "brand": "Nestle",
    "category": "Beverages & Drinks",
    "price": 340,
    "mrp": 380,
    "unit": "100g",
    "usp": "₹340.00 / 100g",
    "rating": 4.8,
    "ratingCount": 4700,
    "image": "images/products/p62.jpg",
    "eta": "10-15 mins",
    "description": "100% pure Robusta coffee beans gently slow-roasted for rich aroma and bold morning lift.",
    "highlights": [
      "100% Pure Coffee",
      "Rich Frothy Aroma",
      "Signature Red Cup Taste"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901019477858"
  },
  {
    "id": "p63",
    "name": "Nestle KitKat 4 Finger Wafer Bar",
    "brand": "Nestle",
    "category": "Snacks & Munchies",
    "price": 40,
    "mrp": 45,
    "unit": "41.5g",
    "usp": "₹96.39 / 100g",
    "rating": 4.8,
    "ratingCount": 5100,
    "image": "images/products/p63.jpg",
    "eta": "10-15 mins",
    "description": "Crisp light wafer fingers smothered in smooth, creamy milk chocolate. Have a break!",
    "highlights": [
      "Crisp Layered Wafers",
      "Smooth Milk Chocolate",
      "Iconic Snap"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901019792017"
  },
  {
    "id": "p64",
    "name": "Nestle Munch Crunchy Chocolate Bar",
    "brand": "Nestle",
    "category": "Snacks & Munchies",
    "price": 20,
    "mrp": 25,
    "unit": "40g",
    "usp": "₹50.00 / 100g",
    "rating": 4.6,
    "ratingCount": 3200,
    "image": "images/products/p64.jpg",
    "eta": "10-15 mins",
    "description": "Light, ultra-crunchy layered wafer covered with rich chocolate coating.",
    "highlights": [
      "Maximum Crunch",
      "Value Pack",
      "Delightful Munch"
    ],
    "isFlashDeal": false,
    "discount": 20,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901020106176"
  },
  {
    "id": "p65",
    "name": "Nestle Everyday Dairy Whitener",
    "brand": "Nestle",
    "category": "Dairy & Breakfast",
    "price": 395,
    "mrp": 440,
    "unit": "1kg",
    "usp": "₹395.0 / kg",
    "rating": 4.6,
    "ratingCount": 2400,
    "image": "images/products/p65.jpg",
    "eta": "10-15 mins",
    "description": "Specially spray-dried milk powder that dissolves instantly to make tea richer and thicker.",
    "highlights": [
      "Thick & Milky Tea",
      "Dissolves Instantly",
      "Long Shelf Life"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901020420335"
  },
  {
    "id": "p66",
    "name": "Haldiram's Nagpur Aloo Bhujia",
    "brand": "Haldiram's",
    "category": "Snacks & Munchies",
    "price": 130,
    "mrp": 150,
    "unit": "400g",
    "usp": "₹32.50 / 100g",
    "rating": 4.8,
    "ratingCount": 6100,
    "image": "images/products/p66.jpg",
    "eta": "10-15 mins",
    "description": "Signature crispy potato sev seasoned with mild mint and Indian chatpata seasoning.",
    "highlights": [
      "Mint Infused",
      "Potato & Gram Flour",
      "India's No. 1 Namkeen"
    ],
    "isFlashDeal": true,
    "discount": 13,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901020734494"
  },
  {
    "id": "p67",
    "name": "Haldiram's Khatta Meetha Mixture",
    "brand": "Haldiram's",
    "category": "Snacks & Munchies",
    "price": 120,
    "mrp": 140,
    "unit": "400g",
    "usp": "₹30.00 / 100g",
    "rating": 4.7,
    "ratingCount": 4300,
    "image": "images/products/p67.jpg",
    "eta": "10-15 mins",
    "description": "Sweet and sour blend of crispy chickpea noodles, rice flakes, green peas, and peanuts.",
    "highlights": [
      "Sweet & Sour Harmony",
      "Crunchy Peanuts",
      "Traditional Tea Snack"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901021048653"
  },
  {
    "id": "p68",
    "name": "Haldiram's Salted Moong Dal",
    "brand": "Haldiram's",
    "category": "Snacks & Munchies",
    "price": 120,
    "mrp": 140,
    "unit": "400g",
    "usp": "₹30.00 / 100g",
    "rating": 4.6,
    "ratingCount": 3100,
    "image": "images/products/p68.jpg",
    "eta": "10-15 mins",
    "description": "Crunchy, light yellow split moong dal roasted in pure oil and dusted with rock salt.",
    "highlights": [
      "Protein Rich Snack",
      "Light & Non-Greasy",
      "Pure Moong Dal"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901021362812"
  },
  {
    "id": "p69",
    "name": "Haldiram's Classic Bhujia Sev",
    "brand": "Haldiram's",
    "category": "Snacks & Munchies",
    "price": 125,
    "mrp": 145,
    "unit": "400g",
    "usp": "₹31.25 / 100g",
    "rating": 4.7,
    "ratingCount": 3900,
    "image": "images/products/p69.jpg",
    "eta": "10-15 mins",
    "description": "Crisp, spicy moth bean and chickpea flour sev seasoned with black pepper and cardamom.",
    "highlights": [
      "Authentic Bikaneri Recipe",
      "Spicy Pepper Kick",
      "Crunchy & Fresh"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901021676971"
  },
  {
    "id": "p70",
    "name": "Haldiram's Royal Soan Papdi",
    "brand": "Haldiram's",
    "category": "Snacks & Munchies",
    "price": 140,
    "mrp": 160,
    "unit": "250g",
    "usp": "₹56.00 / 100g",
    "rating": 4.6,
    "ratingCount": 2800,
    "image": "images/products/p70.jpg",
    "eta": "10-15 mins",
    "description": "Flaky, melt-in-the-mouth festive dessert garnished with pistachio slivers and almonds.",
    "highlights": [
      "Flaky Delicate Texture",
      "Cardamom Aroma",
      "Dry Fruit Toppings"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901021991130"
  },
  {
    "id": "p71",
    "name": "Tata Salt Vacuum Evaporated Iodized",
    "brand": "Tata",
    "category": "Groceries & Staples",
    "price": 27,
    "mrp": 30,
    "unit": "1kg",
    "usp": "₹27.0 / kg",
    "rating": 4.9,
    "ratingCount": 8900,
    "image": "images/products/p71.jpg",
    "eta": "10-15 mins",
    "description": "Desh Ka Namak. Pure vacuum-evaporated table salt fortified with the right amount of iodine.",
    "highlights": [
      "Vacuum Evaporated",
      "Iodine Enriched",
      "Free Flowing"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901022305289"
  },
  {
    "id": "p72",
    "name": "Tata Tea Premium Desh Ki Chai",
    "brand": "Tata",
    "category": "Beverages & Drinks",
    "price": 250,
    "mrp": 285,
    "unit": "500g",
    "usp": "₹50.00 / 100g",
    "rating": 4.7,
    "ratingCount": 4200,
    "image": "images/products/p72.jpg",
    "eta": "10-15 mins",
    "description": "Master blend of big leaves for rich aroma and gently rolled small grains for strong brisk taste.",
    "highlights": [
      "Badi & Choti Patti Blend",
      "Rich Amber Liquor",
      "Desh Ki Chai"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901022619448"
  },
  {
    "id": "p73",
    "name": "Tata Tea Gold Fine Leaf Blend",
    "brand": "Tata",
    "category": "Beverages & Drinks",
    "price": 170,
    "mrp": 190,
    "unit": "250g",
    "usp": "₹68.00 / 100g",
    "rating": 4.8,
    "ratingCount": 3100,
    "image": "images/products/p73.jpg",
    "eta": "10-15 mins",
    "description": "Exquisite blend of strong Assam CTC tea enriched with 15% gently plucked long leaves.",
    "highlights": [
      "15% Long Leaves",
      "Irresistible Aroma",
      "Golden Liquor"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901022933607"
  },
  {
    "id": "p74",
    "name": "Tata Sampann Unpolished Toor Dal",
    "brand": "Tata",
    "category": "Groceries & Staples",
    "price": 175,
    "mrp": 195,
    "unit": "1kg",
    "usp": "₹175.0 / kg",
    "rating": 4.7,
    "ratingCount": 3400,
    "image": "images/products/p74.jpg",
    "eta": "10-15 mins",
    "description": "100% unpolished pigeon peas that retain wholesome natural nutrients and dietary fibre.",
    "highlights": [
      "Unpolished Dal",
      "No Water/Leather Polish",
      "High Plant Protein"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901023247766"
  },
  {
    "id": "p75",
    "name": "Tata Sampann Unpolished Chana Dal",
    "brand": "Tata",
    "category": "Groceries & Staples",
    "price": 155,
    "mrp": 175,
    "unit": "1kg",
    "usp": "₹155.0 / kg",
    "rating": 4.6,
    "ratingCount": 2600,
    "image": "images/products/p75.jpg",
    "eta": "10-15 mins",
    "description": "Nutritious bengal gram dal free from chemical polishing for traditional authentic dal tadka.",
    "highlights": [
      "Zero Chemical Polish",
      "Naturally Wholesome",
      "Rich Earthy Flavour"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901023561925"
  },
  {
    "id": "p76",
    "name": "Cinthol Original Germ Protection Soap",
    "brand": "Godrej",
    "category": "Personal Care",
    "price": 40,
    "mrp": 45,
    "unit": "100g",
    "usp": "₹40.00 / 100g",
    "rating": 4.6,
    "ratingCount": 2400,
    "image": "images/products/p76.jpg",
    "eta": "10-15 mins",
    "description": "Doctor-recommended bathing soap with high TFM formulation to beat body odour and heat rashes.",
    "highlights": [
      "High 79% TFM",
      "Deodorant Action",
      "Protects Skin Health"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901023876084"
  },
  {
    "id": "p77",
    "name": "Good Knight Gold Flash Machine + Refill",
    "brand": "Godrej",
    "category": "Cleaning & Home",
    "price": 75,
    "mrp": 85,
    "unit": "1 Machine + 45ml",
    "usp": "₹75 / 1 Machine + 45ml",
    "rating": 4.7,
    "ratingCount": 3800,
    "image": "images/products/p77.jpg",
    "eta": "10-15 mins",
    "description": "India's most trusted mosquito liquid vaporiser with automatic flash mode every 4 hours.",
    "highlights": [
      "Flash Vapour Release",
      "Knocks Out Mosquitos",
      "Child Safe Mechanism"
    ],
    "isFlashDeal": true,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901024190243"
  },
  {
    "id": "p78",
    "name": "Colgate Strong Teeth Calcium Paste",
    "brand": "Colgate",
    "category": "Personal Care",
    "price": 195,
    "mrp": 220,
    "unit": "500g",
    "usp": "₹39.00 / 100g",
    "rating": 4.8,
    "ratingCount": 6100,
    "image": "images/products/p78.jpg",
    "eta": "10-15 mins",
    "description": "Enriched with Amino Shakti formula that adds natural calcium to tooth enamel for 2x stronger teeth.",
    "highlights": [
      "Amino Shakti Formula",
      "Adds Natural Calcium",
      "Freshens Breath"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901024504402"
  },
  {
    "id": "p79",
    "name": "Colgate MaxFresh Spicy Red Gel",
    "brand": "Colgate",
    "category": "Personal Care",
    "price": 95,
    "mrp": 110,
    "unit": "150g",
    "usp": "₹63.33 / 100g",
    "rating": 4.6,
    "ratingCount": 3700,
    "image": "images/products/p79.jpg",
    "eta": "10-15 mins",
    "description": "Red gel paste packed with cooling crystals that release a burst of intense fresh breath.",
    "highlights": [
      "Cooling Crystals",
      "Spicy Freshness",
      "Long Lasting Confidence"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901024818561"
  },
  {
    "id": "p80",
    "name": "Parachute 100% Pure Coconut Oil",
    "brand": "Marico",
    "category": "Personal Care",
    "price": 220,
    "mrp": 250,
    "unit": "600ml",
    "usp": "₹36.67 / 100ml",
    "rating": 4.9,
    "ratingCount": 7800,
    "image": "images/products/p80.jpg",
    "eta": "10-15 mins",
    "description": "100% edible pure coconut oil extracted from sun-dried roasted Malabar coconuts.",
    "highlights": [
      "100% Pure & Edible",
      "Triple Filtered",
      "Signature Blue Bottle"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901025132720"
  },
  {
    "id": "p81",
    "name": "Saffola Gold Blended Edible Oil",
    "brand": "Marico",
    "category": "Groceries & Staples",
    "price": 175,
    "mrp": 195,
    "unit": "1L",
    "usp": "₹175.0 / L",
    "rating": 4.7,
    "ratingCount": 3200,
    "image": "images/products/p81.jpg",
    "eta": "10-15 mins",
    "description": "Dual-seed technology blending Rice Bran and Sunflower oil to manage cholesterol.",
    "highlights": [
      "LOSORB Technology",
      "Natural Oryzanol",
      "Healthy Heart Oil"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901025446879"
  },
  {
    "id": "p82",
    "name": "Patanjali Dant Kanti Dental Cream",
    "brand": "Patanjali",
    "category": "Personal Care",
    "price": 70,
    "mrp": 80,
    "unit": "200g",
    "usp": "₹35.00 / 100g",
    "rating": 4.5,
    "ratingCount": 3100,
    "image": "images/products/p82.jpg",
    "eta": "10-15 mins",
    "description": "Herbal oral care with Akarkara, Neem, Babool, and Tomar seeds to treat swollen gums.",
    "highlights": [
      "Natural Herbal Actives",
      "Soothes Toothache",
      "Strengthens Gums"
    ],
    "isFlashDeal": false,
    "discount": 12,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901025761038"
  },
  {
    "id": "p83",
    "name": "Patanjali Pure Cow Ghee Diya Wicks",
    "brand": "Patanjali",
    "category": "Pooja Essentials",
    "price": 75,
    "mrp": 90,
    "unit": "Pack of 50 Wicks",
    "usp": "₹1.50 / wick",
    "rating": 4.6,
    "ratingCount": 3500,
    "image": "images/products/p83.jpg",
    "eta": "10-15 mins",
    "description": "Pre-soaked pure cow ghee cotton diya battis for 30-minute steady burning during morning and evening prayers.",
    "highlights": [
      "Wax Free Pure Ghee",
      "Steady 30-Min Burn",
      "Ready to Light"
    ],
    "isFlashDeal": false,
    "discount": 16,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901026075197"
  },
  {
    "id": "p84",
    "name": "Mother Dairy Full Cream Milk",
    "brand": "Mother Dairy",
    "category": "Dairy & Breakfast",
    "price": 56,
    "mrp": 58,
    "unit": "500ml",
    "usp": "₹11.20 / 100ml",
    "rating": 4.7,
    "ratingCount": 2900,
    "image": "images/products/p84.jpg",
    "eta": "10-15 mins",
    "description": "Wholesome pasteurised fresh milk packed with essential energy, protein, and calcium.",
    "highlights": [
      "Pasteurised Fresh",
      "Thick Froth for Chai",
      "Daily Nutrition"
    ],
    "isFlashDeal": false,
    "discount": 3,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901026389356"
  },
  {
    "id": "p85",
    "name": "Mother Dairy Classic Creamy Curd",
    "brand": "Mother Dairy",
    "category": "Dairy & Breakfast",
    "price": 68,
    "mrp": 72,
    "unit": "400g",
    "usp": "₹17.00 / 100g",
    "rating": 4.6,
    "ratingCount": 2100,
    "image": "images/products/p85.jpg",
    "eta": "10-15 mins",
    "description": "Rich set curd prepared under strict hygienic conditions. Creamy texture and mild tang.",
    "highlights": [
      "Set Curd Format",
      "Cooling & Gut-Friendly",
      "Ready to Eat"
    ],
    "isFlashDeal": false,
    "discount": 6,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901026703515"
  },
  {
    "id": "p86",
    "name": "Fortune Sunlite Refined Sunflower Oil",
    "brand": "Fortune",
    "category": "Groceries & Staples",
    "price": 155,
    "mrp": 175,
    "unit": "1L",
    "usp": "₹155.0 / L",
    "rating": 4.6,
    "ratingCount": 3900,
    "image": "images/products/p86.jpg",
    "eta": "10-15 mins",
    "description": "Light, healthy edible cooking oil enriched with Vitamins A and D. Retains natural food taste.",
    "highlights": [
      "Enriched with Vit A & D",
      "Light & Non-Sticky",
      "High Smoke Point"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901027017674"
  },
  {
    "id": "p87",
    "name": "Fortune Special Biryani Basmati Rice",
    "brand": "Fortune",
    "category": "Groceries & Staples",
    "price": 425,
    "mrp": 480,
    "unit": "5kg",
    "usp": "₹85.0 / kg",
    "rating": 4.7,
    "ratingCount": 3300,
    "image": "images/products/p87.jpg",
    "eta": "10-15 mins",
    "description": "Extra-long aged grain basmati rice that elongates up to twice its length upon cooking.",
    "highlights": [
      "Aged Basmati Grains",
      "Elongates on Cooking",
      "Rich Fragrance"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901027331833"
  },
  {
    "id": "p88",
    "name": "MDH Chunky Chat Masala Powder",
    "brand": "MDH",
    "category": "Groceries & Staples",
    "price": 55,
    "mrp": 65,
    "unit": "100g",
    "usp": "₹55.00 / 100g",
    "rating": 4.7,
    "ratingCount": 2800,
    "image": "images/products/p88.jpg",
    "eta": "10-15 mins",
    "description": "Classic tangy seasoning crafted with dry mango powder, black salt, and roasted cumin.",
    "highlights": [
      "Tangy Chatpata Flavor",
      "Asli Masale Sach Sach",
      "Great on Salads & Fruit"
    ],
    "isFlashDeal": false,
    "discount": 15,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901027645992"
  },
  {
    "id": "p89",
    "name": "MDH Deggi Mirch Red Chilli Powder",
    "brand": "MDH",
    "category": "Groceries & Staples",
    "price": 60,
    "mrp": 70,
    "unit": "100g",
    "usp": "₹60.00 / 100g",
    "rating": 4.7,
    "ratingCount": 2900,
    "image": "images/products/p89.jpg",
    "eta": "10-15 mins",
    "description": "Unique blend of Kashmiri and Indian red chillies that imparts glowing red colour without excess heat.",
    "highlights": [
      "Vibrant Natural Red Colour",
      "Mild Balanced Heat",
      "Slow Ground"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901027960151"
  },
  {
    "id": "p90",
    "name": "Cycle Pure Three in One Agarbathies",
    "brand": "Cycle Pure",
    "category": "Pooja Essentials",
    "price": 55,
    "mrp": 65,
    "unit": "Pack of 120 Sticks",
    "usp": "₹0.46 / stick",
    "rating": 4.6,
    "ratingCount": 2200,
    "image": "images/products/p90.jpg",
    "eta": "10-15 mins",
    "description": "Iconic Mysore Cycle Pure Agarbathies with divine Serene, Yugantar, and Jagrane aromas for spiritual harmony.",
    "highlights": [
      "Classic Mysore Heritage",
      "120 Long Sticks",
      "Zero Harmful Charcoal"
    ],
    "isFlashDeal": false,
    "discount": 15,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901028274310"
  },
  {
    "id": "p91",
    "name": "Appy Fizz Sparkling Apple Juice",
    "brand": "Parle Agro",
    "category": "Beverages & Drinks",
    "price": 40,
    "mrp": 45,
    "unit": "750ml",
    "usp": "₹5.33 / 100ml",
    "rating": 4.6,
    "ratingCount": 3600,
    "image": "images/products/p91.jpg",
    "eta": "10-15 mins",
    "description": "The cool drink to hang out with. Crisp bubbly carbonated apple juice with champagne kick.",
    "highlights": [
      "Real Apple Juice Extract",
      "Bubbly Fizz",
      "Party Sensation"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901028588469"
  },
  {
    "id": "p92",
    "name": "Bailley Packaged Drinking Water",
    "brand": "Parle Agro",
    "category": "Beverages & Drinks",
    "price": 20,
    "mrp": 25,
    "unit": "1L",
    "usp": "₹20.0 / L",
    "rating": 4.5,
    "ratingCount": 1800,
    "image": "images/products/p92.jpg",
    "eta": "10-15 mins",
    "description": "Pure, safe drinking water purified through 50-step advanced filtration and UV treatment.",
    "highlights": [
      "50-Step Purification",
      "Essential Added Minerals",
      "Safe & Pure"
    ],
    "isFlashDeal": false,
    "discount": 20,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901028902628"
  },
  {
    "id": "p93",
    "name": "Funfoods Crunchy Peanut Butter",
    "brand": "Dr Oetker",
    "category": "Dairy & Breakfast",
    "price": 485,
    "mrp": 540,
    "unit": "925g",
    "usp": "₹52.43 / 100g",
    "rating": 4.7,
    "ratingCount": 2400,
    "image": "images/products/p93.jpg",
    "eta": "10-15 mins",
    "description": "High-protein crunchy spread packed with 91% slow-roasted premium peanuts.",
    "highlights": [
      "26g Plant Protein",
      "Real Peanut Chunks",
      "Zero Cholesterol"
    ],
    "isFlashDeal": true,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901029216787"
  },
  {
    "id": "p94",
    "name": "Horlicks Classic Malt Health Drink",
    "brand": "GSK",
    "category": "Beverages & Drinks",
    "price": 325,
    "mrp": 360,
    "unit": "500g",
    "usp": "₹65.00 / 100g",
    "rating": 4.7,
    "ratingCount": 3100,
    "image": "images/products/p94.jpg",
    "eta": "10-15 mins",
    "description": "Malted barley nutritional drink clinically proven to make kids taller, stronger, and sharper.",
    "highlights": [
      "Clinically Proven",
      "Bio-available Nutrients",
      "Classic Malt Taste"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901029530946"
  },
  {
    "id": "p95",
    "name": "Complan Royale Chocolate Health Drink",
    "brand": "Zydus Wellness",
    "category": "Beverages & Drinks",
    "price": 310,
    "mrp": 345,
    "unit": "500g",
    "usp": "₹62.00 / 100g",
    "rating": 4.6,
    "ratingCount": 2200,
    "image": "images/products/p95.jpg",
    "eta": "10-15 mins",
    "description": "100% first-class milk protein health drink fortified with 34 vital nutrients for growth.",
    "highlights": [
      "34 Vital Nutrients",
      "100% Milk Protein",
      "Creamy Chocolate Taste"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901029845105"
  },
  {
    "id": "p96",
    "name": "Harpic Power Plus Disinfectant Toilet Cleaner",
    "brand": "Reckitt",
    "category": "Cleaning & Home",
    "price": 155,
    "mrp": 175,
    "unit": "1L",
    "usp": "₹155.0 / L",
    "rating": 4.8,
    "ratingCount": 5900,
    "image": "images/products/p96.jpg",
    "eta": "10-15 mins",
    "description": "10x better stain removal than bleach. Destroys 99.9% germs and dissolves hard limescale.",
    "highlights": [
      "10x Stain Removal",
      "Kills 99.9% Germs",
      "Angled Spout Bottle"
    ],
    "isFlashDeal": true,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901030159264"
  },
  {
    "id": "p97",
    "name": "Dettol Original Liquid Handwash Refill",
    "brand": "Reckitt",
    "category": "Personal Care",
    "price": 80,
    "mrp": 90,
    "unit": "200ml",
    "usp": "₹40.00 / 100ml",
    "rating": 4.8,
    "ratingCount": 6400,
    "image": "images/products/p97.jpg",
    "eta": "10-15 mins",
    "description": "Trusted antiseptic formulation that shields against 100 illness-causing germs.",
    "highlights": [
      "100% Germ Protection",
      "pH Balanced",
      "Original Pine Scent"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901030473423"
  },
  {
    "id": "p98",
    "name": "Dettol Antiseptic Disinfectant Liquid",
    "brand": "Reckitt",
    "category": "Personal Care",
    "price": 165,
    "mrp": 185,
    "unit": "250ml",
    "usp": "₹66.00 / 100ml",
    "rating": 4.9,
    "ratingCount": 7800,
    "image": "images/products/p98.jpg",
    "eta": "10-15 mins",
    "description": "The golden standard of household hygiene for first aid, shaving, bathing, and laundry.",
    "highlights": [
      "First Aid & Surface Cleansing",
      "Proven Antiseptic",
      "Doctors Choice"
    ],
    "isFlashDeal": false,
    "discount": 11,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901030787582"
  },
  {
    "id": "p99",
    "name": "Mortein Fast Knockdown Insect Killer Spray",
    "brand": "Reckitt",
    "category": "Cleaning & Home",
    "price": 175,
    "mrp": 195,
    "unit": "625ml",
    "usp": "₹28.00 / 100ml",
    "rating": 4.6,
    "ratingCount": 2900,
    "image": "images/products/p99.jpg",
    "eta": "10-15 mins",
    "description": "Instant knockdown aerosol spray effective against hidden mosquitoes and cockroaches.",
    "highlights": [
      "Fast Knockdown Action",
      "Reaches Tight Corners",
      "Lemon Fragrance"
    ],
    "isFlashDeal": false,
    "discount": 10,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901031101741"
  },
  {
    "id": "p100",
    "name": "Amul Kool Kesar Almond Flavoured Milk",
    "brand": "Amul",
    "category": "Beverages & Drinks",
    "price": 30,
    "mrp": 35,
    "unit": "200ml",
    "usp": "₹15.00 / 100ml",
    "rating": 4.7,
    "ratingCount": 3100,
    "image": "images/products/p100.jpg",
    "eta": "10-15 mins",
    "description": "Chilled sterilised milk infused with saffron threads, cardamom, and almond essence.",
    "highlights": [
      "Real Kesar Aroma",
      "Rich & Refreshing",
      "Best Served Chilled"
    ],
    "isFlashDeal": false,
    "discount": 14,
    "inStock": true,
    "fssai": "10014022002789",
    "barcode": "8901031415900"
  }
]
};

// search and filter helpers
AppData.getProducts = function(options = {}) {
  let list = [...AppData.products];
  if (options.category && options.category !== 'all') {
    const qCat = options.category.toLowerCase().trim();
    list = list.filter(p => {
      const pCat = p.category.toLowerCase().trim();
      if (pCat === qCat) return true;
      if (qCat.includes('grocery') || qCat.includes('staple')) {
        return pCat.includes('grocer') || pCat.includes('staple');
      }
      if (qCat.includes('dairy') || qCat.includes('breakfast')) {
        return pCat.includes('dairy') || pCat.includes('breakfast');
      }
      if (qCat.includes('snack') || qCat.includes('munch')) {
        return pCat.includes('snack') || pCat.includes('munch');
      }
      if (qCat.includes('beverage') || qCat.includes('drink')) {
        return pCat.includes('beverage') || pCat.includes('drink');
      }
      if (qCat.includes('biscuit') || qCat.includes('cookie')) {
        return pCat.includes('biscuit') || pCat.includes('cookie');
      }
      if (qCat.includes('personal')) {
        return pCat.includes('personal');
      }
      if (qCat.includes('clean') || qCat.includes('home') || qCat.includes('household')) {
        return pCat.includes('clean') || pCat.includes('home') || pCat.includes('household');
      }
      if (qCat.includes('pooja')) {
        return pCat.includes('pooja');
      }
      return false;
    });
  }
  if (options.brand && options.brand !== 'all') {
    const qBrand = options.brand.toLowerCase().trim();
    list = list.filter(p => p.brand.toLowerCase() === qBrand);
  }
  if (options.search) {
    const q = options.search.toLowerCase().trim();
    list = list.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      (p.barcode && p.barcode.includes(q))
    );
  }
  if (options.barcode) {
    const bc = options.barcode.trim();
    list = list.filter(p => p.barcode === bc);
  }
  if (options.flashDeals) {
    list = list.filter(p => p.isFlashDeal || p.discount >= 10);
  }
  if (options.maxPrice) {
    list = list.filter(p => p.price <= options.maxPrice);
  }
  if (options.sort) {
    if (options.sort === 'price-low') list.sort((a, b) => a.price - b.price);
    if (options.sort === 'price-high') list.sort((a, b) => b.price - a.price);
    if (options.sort === 'rating') list.sort((a, b) => b.rating - a.rating);
    if (options.sort === 'discount') list.sort((a, b) => (b.discount || 0) - (a.discount || 0));
  }
  return list;
};

AppData.getProductById = function(id) {
  return AppData.products.find(p => p.id === id);
};

if (typeof window !== 'undefined') {
  window.AppData = AppData;
}
if (typeof global !== 'undefined') {
  global.AppData = AppData;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = AppData;
}
